import test from 'node:test';
import assert from 'node:assert/strict';
import {catalog,parameterDefaults} from '../src/catalog.js';
import {presets,getPreset} from '../src/presets.js';
import {makeNode,clone,validateProject,parseProject,topologicalOrder,removeNode,uniqueId,History,validateExpression,MAX_NODES} from '../src/graph.js';
import {interpolateTrack,insertKey,loopTime,animatedParameters} from '../src/timeline.js';
import {compileGraph} from '../src/compiler.js';
import {crc32,makeZip,frameTimes,fileStem,embedPNGMetadata} from '../src/export.js';
for(const p of presets)test(`schema and shader generation: ${p.id}`,()=>{assert.equal(validateProject(p),p);const c=compileGraph(p);assert(c.fragment.startsWith('#version 300 es'));assert.equal(c.target,p.output);assert(!c.fragment.replace(/\/\/.*$/gm,'').includes('undefined'));assert(c.order.length>0);assert.equal(c.order.at(-1),p.output);});
test('preset clones do not mutate originals',()=>{const p=getPreset('bipolar');p.nodes[1].params.pinch=.5;assert.equal(getPreset('bipolar').nodes[1].params.pinch,.3);});
test('catalog defaults cover every parameter',()=>{for(const[k,v]of Object.entries(catalog)){assert(v.description.length>20);assert(v.equation.length>5);assert.deepEqual(Object.keys(parameterDefaults(k)),Object.keys(v.params));}});
test('unknown catalog type fails',()=>assert.throws(()=>makeNode('not-a-type','x')));
test('duplicate node id fails',()=>{const p=getPreset('bipolar');p.nodes.push(clone(p.nodes[0]));assert.throws(()=>validateProject(p),/duplicate/);});
test('invalid id cannot inject GLSL',()=>{const p=getPreset('bipolar');p.nodes[0].id='x; discard';assert.throws(()=>validateProject(p),/Invalid/);});
test('wrong socket type fails',()=>{const p=getPreset('bipolar');p.nodes.find(n=>n.id==='gas').inputs.geometry='stars';assert.throws(()=>validateProject(p),/expects geometry/);});
test('dangling socket fails',()=>{const p=getPreset('bipolar');p.nodes[1].inputs.p='missing';assert.throws(()=>validateProject(p),/Missing input/);});
test('cycles including disconnected nodes fail',()=>{const p=getPreset('bipolar');p.nodes.push(makeNode('transform','loopA',{p:'loopB'}),makeNode('transform','loopB',{p:'loopA'}));assert.throws(()=>validateProject(p),/Cycle/);});
test('self-cycle fails',()=>{const p=getPreset('bipolar');p.nodes.push(makeNode('transform','loop',{p:'loop'}));assert.throws(()=>validateProject(p),/Cycle/);});
test('unknown params fail',()=>{const p=getPreset('bipolar');p.nodes[1].params.unexpected=1;assert.throws(()=>validateProject(p),/Unknown parameter/);});
test('nonfinite parameters fail',()=>{const p=getPreset('bipolar');p.nodes[1].params.pinch=NaN;assert.throws(()=>validateProject(p),/finite/);});
test('out of range parameters fail',()=>{const p=getPreset('bipolar');p.nodes[1].params.pinch=-1;assert.throws(()=>validateProject(p),/finite/);});
test('bad exposure, duration and zoom fail',()=>{for(const edit of [p=>p.exposure=9,p=>p.duration=0,p=>p.view.zoom=0]){const p=getPreset('bipolar');edit(p);assert.throws(()=>validateProject(p));}});
test('parse rejects schema and oversize data',()=>{assert.throws(()=>parseProject('{"schemaVersion":2}'));assert.throws(()=>parseProject('x'.repeat(1_000_001)),/1 MB/);});
test('unknown output fails',()=>{const p=getPreset('bipolar');p.output='bad';assert.throws(()=>validateProject(p),/output/);});
test('graph size is bounded',()=>{const p=getPreset('bipolar');while(p.nodes.length<=MAX_NODES)p.nodes.push(makeNode('solid',`s${p.nodes.length}`));assert.throws(()=>validateProject(p),/components/);});
test('reachable shared expressions compile only once',()=>{const c=compileGraph(getPreset('bipolar'));assert.equal(c.order.filter(x=>x==='turbulence').length,1);assert(c.order.indexOf('turbulence')<c.order.indexOf('cloud'));});
test('unreachable nodes do not generate shader code',()=>{const p=getPreset('bipolar');p.nodes.push(makeNode('solid','unused'));assert(!compileGraph(p).order.includes('unused'));});
test('disabling an output prunes all upstream computation',()=>{const p=getPreset('bipolar');p.nodes.find(n=>n.id===p.output).enabled=false;assert.deepEqual(compileGraph(p).order,['final']);});
test('unconnected coordinate socket is zero, not implicit world space',()=>{const p=getPreset('bipolar');delete p.nodes[1].inputs.p;assert(compileGraph(p).fragment.includes('nebulaGeometry(vec2(0),'));});
test('isolated scalar, coordinate and geometry use diagnostic conversions',()=>{const p=getPreset('bipolar');assert.equal(compileGraph(p,'shell').type,'geometry');assert.equal(compileGraph(p,'turbulence').type,'scalar');assert.equal(compileGraph(p,'space').type,'coord');});
test('changing numbers preserves shader source',()=>{const p=getPreset('bipolar'),a=compileGraph(p).fragment;p.nodes[1].params.pinch=.6;assert.equal(a,compileGraph(p).fragment);});
test('custom expression edits change shader source',()=>{const p=getPreset('kaleidoscope'),a=compileGraph(p).fragment;p.nodes.find(n=>n.id==='petals').params.expression='0.1';assert.notEqual(a,compileGraph(p).fragment);});
test('expression lexical restrictions reject statements and injection',()=>{for(const s of ['return 1.0;','for(;;){}','x = 2.0','x++','x/*hide*/','window.alert(1);','vec3[2](1)','#define x y'])assert.throws(()=>validateExpression(s));});
test('expression comparisons, ternaries and whitespace are allowed',()=>{for(const s of ['x >= 0.0 ? 1.0 : 0.0','a == b ? 0.0 : 1.0','sin( x + t )','vec2(x,y)'])assert.equal(validateExpression(s),s);});
test('delete removes downstream references and tracks',()=>{const p=getPreset('lensing');removeNode(p,'lens');assert(!p.nodes.find(n=>n.id==='sourcePosition').inputs.p);assert.equal(p.tracks.length,0);validateProject(p);});
test('delete final chooses existing fallback',()=>{const p=getPreset('bipolar');removeNode(p,'final');assert(p.nodes.some(n=>n.id===p.output));});
test('cannot delete the final remaining node',()=>{const p=getPreset('bipolar');p.nodes=[makeNode('solid','only')];p.output='only';assert.throws(()=>removeNode(p,'only'));});
test('unique ids skip existing identifiers',()=>{const p=getPreset('bipolar');p.nodes.push(makeNode('solid','solid1'));assert.equal(uniqueId(p,'solid'),'solid2');});
test('history undo / redo snapshots are independent',()=>{const h=new History(2),a=getPreset('bipolar');h.push(a);a.title='new';const old=h.undo(a);assert.equal(old.title,'Bipolar nebula');assert.equal(h.redo(old).title,'new');});
test('new edit invalidates redo',()=>{const h=new History();h.push(getPreset('bipolar'));h.undo(getPreset('water'));h.push(getPreset('water'));assert.equal(h.redo(getPreset('water')),null);});
const track={node:'x',param:'p',interpolation:'linear',keys:[{time:0,value:0},{time:2,value:10},{time:4,value:0}]};
test('linear keyframe interpolation and endpoints',()=>{assert.equal(interpolateTrack(track,-1,99),0);assert.equal(interpolateTrack(track,1,99),5);assert.equal(interpolateTrack(track,2,99),10);assert.equal(interpolateTrack(track,5,99),0);});
test('smooth and hold keyframe interpolation',()=>{assert.equal(interpolateTrack({...track,interpolation:'smooth'},.5,0),1.5625);assert.equal(interpolateTrack({...track,interpolation:'hold'},1,0),0);});
test('empty keyframe track falls back to base',()=>assert.equal(interpolateTrack({...track,keys:[]},2,123),123));
test('inserting a key replaces same timestamp and keeps sort',()=>{const p=getPreset('bipolar');insertKey(p,'shell','pinch',2,.6);insertKey(p,'shell','pinch',0,.3);insertKey(p,'shell','pinch',2,.4);assert.deepEqual(p.tracks[0].keys,[{time:0,value:.3},{time:2,value:.4}]);validateProject(p);});
test('keyframe sampling does not mutate base params',()=>{const p=getPreset('lensing'),n=p.nodes.find(n=>n.id==='lens');assert.equal(animatedParameters(p,n,4).strength,.05);assert.equal(n.params.strength,1.45);});
test('keyframe order, duplicate, and domain violations rejected',()=>{for(const keys of [[{time:2,value:.3},{time:1,value:.3}],[{time:1,value:.3},{time:1,value:.4}],[{time:9,value:.4}],[{time:0,value:8}]]){const p=getPreset('bipolar');p.tracks=[{node:'shell',param:'pinch',interpolation:'smooth',keys}];assert.throws(()=>validateProject(p));}});
test('duration decrease cannot silently delete animation keys',()=>{const p=getPreset('lensing');p.duration=4;assert.throws(()=>validateProject(p));});
test('color tracks are not silently accepted',()=>{const p=getPreset('peacock');p.tracks=[{node:'background',param:'color',interpolation:'linear',keys:[]}];assert.throws(()=>validateProject(p),/track/);});
test('loop time wraps negative and positive values',()=>{assert.equal(loopTime(9,8),1);assert.equal(loopTime(-1,8),7);});
test('CRC32 standard check value',()=>assert.equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926));
test('ZIP header, CRC, central directory and end record',async()=>{const bytes=new Uint8Array(await makeZip([{name:'a.txt',data:'hello'}]).arrayBuffer()),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(14,true),0x3610a686);assert.equal(v.getUint32(bytes.length-22,true),0x06054b50);assert.equal(v.getUint16(bytes.length-12,true),1);});
test('ZIP rejects traversal and duplicate names',()=>{for(const name of ['../evil','/absolute','x\\y'])assert.throws(()=>makeZip([{name,data:'x'}]));assert.throws(()=>makeZip([{name:'a',data:'x'},{name:'a',data:'y'}]));});
test('frame sequence uses exact timestamps and excludes end',()=>{assert.deepEqual(frameTimes(1,4),[0,.25,.5,.75]);assert.equal(frameTimes(8,24).length,192);assert.throws(()=>frameTimes(11,24),/240/);assert.throws(()=>frameTimes(1,NaN));});
test('filename sanitization has a safe fallback',()=>{assert.equal(fileStem('My / test…'),'my-test');assert.equal(fileStem('::::'),'equation-studio');});
test('PNG metadata insertion keeps IEND and UTF8 data',async()=>{const minimal=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0,73,69,78,68,174,66,96,130]);const bytes=new Uint8Array(await (await embedPNGMetadata(new Blob([minimal]),{title:'λ studio'})).arrayBuffer());assert.equal(new TextDecoder().decode(bytes.slice(12,16)),'iTXt');assert(new TextDecoder().decode(bytes).includes('λ studio'));assert.deepEqual([...bytes.slice(-12)],[...minimal.slice(-12)]);});
test('PNG metadata rejects other formats',async()=>assert.rejects(()=>embedPNGMetadata(new Blob(['jpeg']),{})));
