/** Regenerate the human-readable catalog and portable example project files.
 * Run: node tools/generate_catalog.js (Node 20+, no npm dependencies).
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { catalog } from '../src/catalog.js';
import { presets, getPreset } from '../src/presets.js';
const root = new URL('../', import.meta.url);
await mkdir(new URL('examples/projects/', root), { recursive: true });
const cell = value => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
let text = '# Component catalog\n\nGenerated from `src/catalog.js`. This is the same metadata used by the browser palette, inspector, graph type checker and shader compiler. Do not edit this file by hand. Run `node tools/generate_catalog.js` after changing the catalog.\n\n';
text += `**${Object.keys(catalog).length} component kinds; ${presets.length} scene presets.** Unconnected/disabled outputs are typed zero. Color layers use straight RGB radiance and coverage, not pre-clipped pixels.\n\n`;
text += '| Type ID | Name | Category | Output | Inputs |\n|---|---|---|---|---|\n';
for (const [id, d] of Object.entries(catalog)) {
    text += `| \`${id}\` | ${cell(d.name)} | ${cell(d.category)} | ${d.output} | ${Object.entries(d.inputs).map(([name,type])=>`${name}: ${type}`).join(', ') || 'none'} |\n`;
}
for (const [id, d] of Object.entries(catalog)) {
    text += `\n## ${d.name}\n\nID: \`${id}\` · **${d.output}** · ${d.category}\n\n${d.description}\n\n**Expression / role:** ${d.equation}\n\n`;
    if (Object.keys(d.params).length) {
        text += '| Parameter | Kind | Default | Allowed interval | Intent |\n|---|---|---|---|---|\n';
        for (const [p,s] of Object.entries(d.params)) {
            text += `| \`${p}\` | ${s.kind} | ${cell(s.value)} | ${s.kind==='number'?`${s.min} to ${s.max}, control step ${s.step}`:'—'} | ${cell(s.help || s.label)} |\n`;
        }
    } else text += 'No parameters.\n';
}
await writeFile(new URL('docs/COMPONENTS.md', root), text);
for (const p of presets) await writeFile(new URL(`examples/projects/${p.id}.json`, root), JSON.stringify(getPreset(p.id), null, 2)+'\n');
console.log(`Wrote ${Object.keys(catalog).length} component entries and ${presets.length} projects to ${fileURLToPath(root)}`);
