/** Regenerate the human-readable component catalog and the portable example
 * project files from src/catalog.js, src/concepts.js and src/presets.js.
 * Run: node tools/generate_catalog.js (Node 20+, no npm dependencies).
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { catalog, typeLabels } from '../src/catalog.js';
import { concepts } from '../src/concepts.js';
import { forkable, forkProgram } from '../src/fork.js';
import { makeNode } from '../src/graph.js';
import { presets, getPreset } from '../src/presets.js';
const root = new URL('../', import.meta.url);
await mkdir(new URL('examples/projects/', root), { recursive: true });
const cell = value => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
const inlineMath = tex => `$${tex}$`;
const bypassText = d => d.bypass ? `passes \`${d.bypass}\` through` : 'outputs zero';
const anchor = title => title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
let text = '# Component catalog\n\nGenerated from `src/catalog.js` and `src/concepts.js`, the same metadata that drives the editor’s palette, inspector, playground, formula sheet, type checker and shader compiler. Do not edit this file by hand; run `node tools/generate_catalog.js` after changing the catalog.\n\n';
text += `**${Object.keys(catalog).length} component kinds; ${presets.length} scene presets; ${Object.keys(concepts).length} ideas explained.** Unconnected inputs are typed zero. A disabled (bypassed) component passes its bypass input through unchanged, or outputs zero when it has none. Color layers use straight RGB radiance and coverage, not pre-clipped pixels. Components marked *editable* open as an equivalent equation with **✎ Edit**; for those written out line by line, the equation is listed under their steps.\n\n`;
text += '| Type ID | Name | Category | Output | Inputs | When bypassed | Editable |\n|---|---|---|---|---|---|---|\n';
for (const [id, d] of Object.entries(catalog)) {
    text += `| \`${id}\` | [${cell(d.name)}](#${anchor(d.name)}) | ${cell(d.category)} | ${typeLabels[d.output]} | ${Object.entries(d.inputs).map(([name, type]) => `${name}: ${type}`).join(', ') || 'none'} | ${bypassText(d)} | ${d.custom ? 'is an equation' : forkable(id) ? 'yes' : 'no'} |\n`;
}
for (const [id, d] of Object.entries(catalog)) {
    text += `\n## ${d.name}\n\nID: \`${id}\` · output **${typeLabels[d.output]}**${d.outputSymbols.length ? ` (${d.outputSymbols.map(inlineMath).join(', ')})` : ''} · ${d.category} · role ${d.role} · when bypassed it ${bypassText(d)}\n\n${d.description}\n\n`;
    text += '**How it is computed**\n\n';
    d.steps.forEach((s, i) => {
        text += `${i + 1}. ${i === d.steps.length - 1 ? '*Result.* ' : ''}${s.text}\n\n   $$\n   ${s.tex}\n   $$\n\n`;
    });
    const symbols = [];
    for (const [socket, kind] of Object.entries(d.inputs)) {
        symbols.push(`| ${inlineMath(d.inputSymbols[socket] || socket)} | input \`${socket}\` | ${typeLabels[kind]} |`);
    }
    for (const [symbol, meaning] of d.notes) {
        symbols.push(`| ${inlineMath(symbol)} | | ${cell(meaning)} |`);
    }
    if (symbols.length) {
        text += `| Symbol | Name | Meaning |\n|---|---|---|\n${symbols.join('\n')}\n`;
    }
    if (Object.keys(d.params).length) {
        text += '\n| Parameter | Symbol | Default | Range | What it does |\n|---|---|---|---|---|\n';
        for (const [p, s] of Object.entries(d.params)) {
            const range = s.kind === 'number' ? `${s.min} to ${s.max} (step ${s.step})` : '—';
            text += `| ${cell(s.label)} \`${p}\` | ${s.symbol ? inlineMath(s.symbol) : '—'} | ${cell(s.kind === 'expression' ? `\`${s.value}\`` : s.value)} | ${range} | ${cell(s.help || s.label)} |\n`;
        }
    }
    else {
        text += '\nNo parameters.\n';
    }
    if (d.source) {
        const program = forkProgram(makeNode(id, 'x')).expression.split('\n').filter(line => !line.startsWith('//'));
        text += `\n**As an equation** (what ✎ Edit opens, at the default values)\n\n\`\`\`text\n${program.join('\n')}\n\`\`\`\n`;
    }
    if (d.curve) {
        text += `\n*Key function shown in the editor:* ${d.curve.title.toLowerCase()} (${d.curve.y} against ${d.curve.x}).\n`;
    }
    if (d.concepts.length) {
        text += `\n*Ideas behind it:* ${d.concepts.map(c => `[${concepts[c].title}](#${anchor(concepts[c].title)})`).join(' · ')}\n`;
    }
}
text += '\n# Ideas behind the equations\n\nThe recurring mathematical ideas the components use. In the editor each one appears as a card with a plot you can adjust.\n';
for (const c of Object.values(concepts)) {
    text += `\n## ${c.title}\n\n${c.tex ? `$$\n${c.tex}\n$$\n\n` : ''}${c.text}\n`;
    const users = Object.entries(catalog).filter(([, d]) => d.concepts.includes(Object.keys(concepts).find(k => concepts[k] === c))).map(([, d]) => `[${d.name}](#${anchor(d.name)})`);
    if (users.length) {
        text += `\nUsed by: ${users.join(', ')}.\n`;
    }
}
await writeFile(new URL('docs/COMPONENTS.md', root), text);
for (const p of presets) {
    await writeFile(new URL(`examples/projects/${p.id}.json`, root), JSON.stringify(getPreset(p.id), null, 2) + '\n');
}
console.log(`Wrote ${Object.keys(catalog).length} component entries, ${Object.keys(concepts).length} ideas and ${presets.length} projects to ${fileURLToPath(root)}`);
