/** Regenerate the human-readable component catalog and the portable example
 * project files from src/catalog.js and src/presets.js.
 * Run: node tools/generate_catalog.js (Node 20+, no npm dependencies).
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { catalog, typeLabels } from '../src/catalog.js';
import { presets, getPreset } from '../src/presets.js';
const root = new URL('../', import.meta.url);
await mkdir(new URL('examples/projects/', root), { recursive: true });
const cell = value => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
const inlineMath = tex => `$${tex}$`;
const bypassText = d => d.bypass ? `passes \`${d.bypass}\` through` : 'outputs zero';
let text = '# Component catalog\n\nGenerated from `src/catalog.js`, the same metadata that drives the editor’s palette, inspector, equations, type checker and shader compiler. Do not edit this file by hand; run `node tools/generate_catalog.js` after changing the catalog.\n\n';
text += `**${Object.keys(catalog).length} component kinds; ${presets.length} scene presets.** Unconnected inputs are typed zero. A disabled (bypassed) component passes its bypass input through unchanged, or outputs zero when it has none. Color layers use straight RGB radiance and coverage, not pre-clipped pixels.\n\n`;
text += '| Type ID | Name | Category | Output | Inputs | When bypassed |\n|---|---|---|---|---|---|\n';
for (const [id, d] of Object.entries(catalog)) {
    text += `| \`${id}\` | ${cell(d.name)} | ${cell(d.category)} | ${typeLabels[d.output]} | ${Object.entries(d.inputs).map(([name, type]) => `${name}: ${type}`).join(', ') || 'none'} | ${bypassText(d)} |\n`;
}
for (const [id, d] of Object.entries(catalog)) {
    text += `\n## ${d.name}\n\nID: \`${id}\` · output **${typeLabels[d.output]}** · ${d.category} · role ${d.role} · when bypassed it ${bypassText(d)}\n\n${d.description}\n\n`;
    text += d.tex.map(line => `$$\n${line}\n$$\n`).join('\n');
    const symbols = [];
    for (const [socket, kind] of Object.entries(d.inputs)) {
        symbols.push(`| ${inlineMath(d.inputSymbols[socket] || socket)} | input \`${socket}\` | ${typeLabels[kind]} |`);
    }
    for (const [symbol, meaning] of d.notes) {
        symbols.push(`| ${inlineMath(symbol)} | | ${cell(meaning)} |`);
    }
    if (symbols.length) {
        text += `\n| Symbol | Name | Meaning |\n|---|---|---|\n${symbols.join('\n')}\n`;
    }
    if (Object.keys(d.params).length) {
        text += '\n| Parameter | Symbol | Default | Range | What it does |\n|---|---|---|---|---|\n';
        for (const [p, s] of Object.entries(d.params)) {
            const range = s.kind === 'number' ? `${s.min} to ${s.max} (step ${s.step})` : '—';
            text += `| ${cell(s.label)} \`${p}\` | ${s.symbol ? inlineMath(s.symbol) : '—'} | ${cell(s.kind === 'expression' ? `\`${s.value}\`` : s.value)} | ${range} | ${cell(s.help || s.label)} |\n`;
        }
    }
    else {
        text += '\nNo parameters.\n';
    }
}
await writeFile(new URL('docs/COMPONENTS.md', root), text);
for (const p of presets) {
    await writeFile(new URL(`examples/projects/${p.id}.json`, root), JSON.stringify(getPreset(p.id), null, 2) + '\n');
}
console.log(`Wrote ${Object.keys(catalog).length} component entries and ${presets.length} projects to ${fileURLToPath(root)}`);
