#!/usr/bin/env python3
"""Assemble measured results into docs/VALIDATION.md.

Run the test suites first and capture their output:

    node --test --test-reporter=tap tests/*.test.js > docs/NODE_TEST_RESULTS.txt 2>&1
    (cd reference/nebula_rewrite && python -m unittest discover -s tests -v 2> ../../docs/CPU_TEST_RESULTS.txt)
    python tools/gpu_validate.py     # docs/GPU_VALIDATION.json
    python tools/workflow_check.py   # docs/WORKFLOW_VALIDATION.json

Every number in the report is read from those files; nothing is typed in by hand.
"""
from pathlib import Path
import datetime
import json
import re
ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'docs'


def count(pattern, text, default='?'):
    match = re.search(pattern, text, re.M)
    return match.group(1) if match else default


gpu = json.loads((DOCS / 'GPU_VALIDATION.json').read_text(encoding='utf-8'))
workflow = json.loads((DOCS / 'WORKFLOW_VALIDATION.json').read_text(encoding='utf-8'))
node_log = (DOCS / 'NODE_TEST_RESULTS.txt').read_text(encoding='utf-8')
cpu_log = (DOCS / 'CPU_TEST_RESULTS.txt').read_text(encoding='utf-8')
native = gpu['native_image_comparison']
fields = gpu['raw_field_comparison']['fields']
checks = gpu['checks']
names = [c['name'] for c in checks]
presets = sum(1 for n in names if n.startswith('render + finite values: '))
moving = sum(1 for n in names if n.startswith('stateless visible animation: '))
previews = sum(1 for n in names if n.startswith('preview atlas renders every node: '))
components = count(r'all (\d+) component types', ' '.join(names))
probes = gpu['raw_field_comparison']['sample_count']
node_pass, node_fail = count(r'^(?:# |\S )pass (\d+)', node_log), count(r'^(?:# |\S )fail (\d+)', node_log, '0')
cpu_ran = count(r'Ran (\d+) tests', cpu_log)
cpu_ok = 'OK' in cpu_log.splitlines()[-1] if cpu_log.strip() else False
try:
    date = datetime.date.fromisoformat(gpu.get('date', datetime.date.today().isoformat())).strftime('%d %B %Y').lstrip('0')
except ValueError:
    date = gpu.get('date', 'unknown')
workflow_names = '; '.join(c['name'] for c in workflow['checks'] if not c['name'].startswith('No uncaught'))
text = f'''# Validation and known limits

Validation date: **{date}**. This is an executed implementation, not a mock-up or a shader listing that was never compiled. Every figure below is generated by `tools/write_validation_report.py` from the captured test outputs.

## Executed test groups

| Group | Result | Evidence |
|---|---|---|
| JavaScript unit tests | **{node_pass} passed, {node_fail} failed** | [Captured output](NODE_TEST_RESULTS.txt) |
| Retained Python source tests | **{cpu_ran} ran, {'all passed' if cpu_ok else 'see log'}** | [Captured output](CPU_TEST_RESULTS.txt) |
| Actual WebGL scene rendering | **{presets}/{presets} presets** at 640 × 384, with finite-output checks | [GPU report](GPU_VALIDATION.json) |
| Actual component shaders | **{components}/{components} component kinds** compiled and rendered with finite default outputs | [GPU report](GPU_VALIDATION.json) |
| Per-node preview atlas | **{previews}/{previews} presets** rendered a finite thumbnail for every node from one shared program | [GPU report](GPU_VALIDATION.json) |
| Contribution view | Highlights only pixels the node changes; an unreachable node changes none | [GPU report](GPU_VALIDATION.json) |
| Stateless animation | **{moving}/{moving} tested moving presets** changed at t=2.3 and repeated the original t=0 frame exactly on this backend | [GPU report](GPU_VALIDATION.json) |
| Original source raw fields | **{probes} native-grid points**, seven field groups, actual float framebuffer readback vs float64 CPU | [GPU report](GPU_VALIDATION.json) |
| Original source native image | **2000 × 1200** rendered and compared without alignment or color fitting | [GPU PNG](../gallery/bipolar_2000x1200_gpu.png) |
| Editor workflows | {len(workflow['checks'])} checks: {workflow_names} | [Workflow report](WORKFLOW_VALIDATION.json) |
| GPU-unavailable fallback | Visible error panel, export rejected, no uncaught JS errors | [Failure report](FAILURE_VALIDATION.json) |
| Local server | Root page, JS MIME type and port-collision handling passed | [HTTP report](HTTP_VALIDATION.json) |

The unit tests cover all preset models, graph types and traversal helpers, cycles including disconnected cycles, missing/disabled inputs, reachable sharing, bounds, custom-expression restrictions, structural/uniform changes, the contribution and preview compile modes, deletion, history, interpolation and key retiming, camera arithmetic and ruler ticks, graph layout, snapshots, deterministic frame times, ZIP CRC/path checks, and PNG metadata construction. The Python tests retain an independently written scalar source transcription as well as image/CLI/composition checks.

Browser workflow tests exercise actual event handlers, pointer gestures and downloads, not only direct function calls. PNG metadata was independently decoded with Pillow after loading all PNG chunks. Four-frame sequence ZIP output was independently checked using Python's zipfile module, including CRCs, frame dimensions, exact timestamps and differing frame pixels. A WebM was downloaded through MediaRecorder. The metadata-extraction utility also recovers the PNG's project without Pillow.

## Native GPU versus CPU measurement

The comparison uses the same source sampling grid, defaults and display function. No crop search, spatial alignment, fitted palette, blur or histogram correction was applied. Each error is measured across RGB **channel samples**, not a count of whole pixels.

| Metric | Result |
|---|---:|
| Mean absolute channel error, 0–255 | {native['mae_0_255']:.6f} |
| Root mean squared channel error, 0–255 | {native['rmse_0_255']:.6f} |
| 95th percentile absolute channel error | {native['p95_absolute_error']:.0f} |
| 99th percentile absolute channel error | {native['p99_absolute_error']:.0f} |
| Largest single-channel error | **{native['max_error']}** |
| RGB Pearson correlation | {native['rgb_pearson_correlation']:.9f} |
| PSNR | {native['psnr_db']:.4f} dB |

**This is not byte-for-byte identity.** The relatively small average error coexists with large rare outliers near very sharp features. Correlation is a similarity statistic, not “percent accuracy.” The highest-frequency star/filament terms are sensitive to float32 coordinate and trigonometric rounding. The retained CPU image is itself a documented transcription of the supplied equations, not a recovered native original from the artist; agreement between implementations cannot prove the historical transcription is infallible.

The native draw plus readback took approximately **{native['render_plus_readback_ms'] / 1000:.2f} seconds** in the test environment ({gpu['test_environment']}). This number includes driver behavior and may include compilation; concurrent tests also affect it. It is **not a hardware benchmark** and should not be used to predict a user's frame rate.

## Raw field comparison

Readback used a one-pixel RGBA32F framebuffer at each selected source-grid position. These are actual field values before false-color diagnostic mapping, exposure or final display conversion. The seeded sample set, coordinates and complete statistics are in the JSON report.

| Field group | Mean absolute error | Maximum absolute error |
|---|---:|---:|
'''
for name, stats in fields.items():
    text += f"| {name} | {stats['mean_abs_error']:.9g} | {stats['max_abs_error']:.9g} |\n"
text += f'''
The source's fixed band-angle constants and powers are evaluated once in JavaScript float64 before being emitted as GLSL constants. An initial implementation that evaluated large fixed angles in shader precision had substantially worse raw-field disagreement. The delivered constant-folded version above is what the tests and screenshots use. High-frequency position-dependent calculations still use shader precision; constant folding cannot make those bitwise equivalent to float64.

The zero-strength lens-map identity was also verified through raw float readback. Offscreen probes and snapshots were checked to leave the visible canvas untouched. Changing a numeric parameter was checked to reuse the same linked program, rather than forcing a compilation. Nonfinite tests check output RGBA, not merely the final displayed RGB.

## Browser verification and portability boundary

The tested browser was **Chromium {workflow['browser_version']}** with the **{gpu['gpu']['renderer']}** backend, reported highp precision of {gpu['gpu']['precisionBits']} bits, and `EXT_color_buffer_float` {'available' if gpu['gpu']['rawFields'] else 'unavailable'}. The automated suites select the ANGLE/SwiftShader software backend by default so that measurements are comparable across machines; the software backend still executes the actual shipped WebGL 2/GLSL code rather than a substitute Python renderer. Set `EQUATION_STUDIO_HARDWARE_GPU=1` to run them on the browser's own backend instead.

The tests loaded the **actual bundled HTML and JavaScript into an in-memory about:blank page**, so no browser policy is required and none was changed. Local file and localhost browser navigation were not end-to-end verified by these suites. The local static server was independently checked using ordinary loopback HTTP requests. Firefox, Safari, iOS and physical-GPU/browser combinations remain untested.

Desktop (1600 × 1030), tablet-width (860 × 1000) and mobile-width (390 × 844) screenshots were captured from the running app. These test responsive layout in Chromium; they are not device certification. Custom equation failure was tested to preserve the last valid project. Connection-cycle failure was tested to restore both the model and visible dropdown. GPU context loss and restoration were exercised using the test extension, including re-enabling float-buffer support and reading a field afterward.

Real-time recording produced a decodable video but does **not** guarantee a requested frame count on a software backend. The PNG sequence is the deterministic export path. Reference-image auto-alignment, a full accessibility audit, hardware performance matrix, memory-stress testing at all maximum limits, and browser codec matrix are not completed.

## Repeat the tests

Run from the project root:

```bash
node --test tests/*.test.js
python3 tools/build.py

# Optional Python reference dependencies and tests
python3 -m pip install -r reference/nebula_rewrite/requirements.txt
(cd reference/nebula_rewrite && python3 -m unittest discover -s tests -v)

# Optional browser-testing dependencies
python3 -m pip install playwright numpy pillow
python3 -m playwright install chromium     # or set EQUATION_STUDIO_CHROMIUM=/path/to/chromium
python3 tools/browser_check.py
python3 tools/workflow_check.py
python3 tools/gpu_validate.py
python3 tools/write_validation_report.py
```

On a headless Linux machine whose ANGLE driver needs X11, prefix a browser test with `xvfb-run -a`. Ordinary app launches do not force the software backend; the browser chooses its supported GPU backend. Do not alter managed browser policies to run these tests.

Full GPU validation can take several minutes on a software renderer. Run the browser suites sequentially when comparing performance or video capture behavior; concurrent software rendering competes for CPU resources. See [Development](DEVELOPMENT.md) for the complete regeneration checklist.

## What has not been verified

The five new subject studies do not have recovered original formula sheets or native reference images. No pixel-fidelity claim is made about those artworks. The Hedgehog/Fire video algorithms, third-party Rust implementation and unavailable thread/reply content were not reconstructed. The new astronomical/natural effects are not validated physical simulations. See the evidence ledger in [Research](RESEARCH.md).
'''
(DOCS / 'VALIDATION.md').write_text(text, encoding='utf-8', newline='\n')
print('Wrote docs/VALIDATION.md')
