/** Single source of truth for the node palette, type system, UI and shader compiler.
 * To add a component: define its typed sockets, parameter schema, equation, and emit().
 * emit() receives GLSL expressions, not JS values. Numerical parameters are uniforms.
 */
const num = (label, value, min, max, step, help = '') => ({ kind: 'number', label, value, min, max, step, help });
const rgb = (label, value) => ({ kind: 'color', label, value, help: 'Linear radiance multiplier; display conversion happens only after composition.' });
const expr = (value) => ({ kind: 'expression', label: 'GLSL expression', value, help: 'Use p, x, y, r, theta, t, a and b. Expression only: no statements, loops, declarations, or JavaScript.' });
const node = (name, category, output, inputs, params, equation, description, emit) => ({ name, category, output, inputs, params, equation, description, emit });
export const catalog = {
    coordinates: node('Image coordinates', 'Coordinates', 'coord', {}, {}, 'p = (pixel − center) × worldUnitsPerPixel', 'World-space coordinates. Native 2000 × 1200 sampling keeps the original +1/840 offset on each axis. All image layers share this field.', () => 'p'),
    transform: node('Translate · rotate · scale', 'Coordinates', 'coord', { p: 'coord' }, {
        x: num('Center X', 0, -5, 5, 0.01), y: num('Center Y', 0, -5, 5, 0.01), angle: num('Rotation', 0, -6.28, 6.28, 0.01), scale: num('Scale', 1, 0.05, 5, 0.01), stretch: num('Vertical stretch', 1, 0.1, 4, 0.01)
    }, 'q = R(−angle) (p − center) / scale', 'Inverse-map world pixels into local object coordinates. This moves the object without stretching a stored picture.', (i, u) => `rotate2(${i.p}-vec2(${u.x},${u.y}),-${u.angle})/vec2(${u.scale},${u.scale}*${u.stretch})`),
    vortex: node('Localized vortex', 'Coordinates', 'coord', { p: 'coord' }, { strength: num('Twist', 4, -16, 16, 0.1), radius: num('Influence radius', 1, 0.02, 4, 0.02), speed: num('Rotation speed', 0, -2, 2, 0.01) }, 'q = R(strength · exp(−r²/radius²) + speed · t) p', 'A smooth local coordinate twist. Send any texture, star field or silhouette through this map.', (i, u) => `vortex(${i.p},${u.strength},${u.radius},${u.speed}*u_time)`),
    domainwarp: node('Turbulent coordinate warp', 'Coordinates', 'coord', { p: 'coord' }, { amplitude: num('Displacement', 0.4, 0, 2, 0.01), frequency: num('Frequency', 2, 0.1, 12, 0.1), speed: num('Flow speed', 0.1, -2, 2, 0.01) }, 'q = p + amplitude · (noise₁(p,t), noise₂(p,t))', 'Independent smooth fields displace the two coordinate axes. A reusable alternative to drawing complicated boundaries directly.', (i, u) => `domainWarp(${i.p},${u.amplitude},${u.frequency},u_time*${u.speed})`),
    polar: node('Polar coordinates', 'Coordinates', 'coord', { p: 'coord' }, { angleScale: num('Angle scale', 1, 0.1, 12, 0.1), radiusScale: num('Radius scale', 1, 0.1, 12, 0.1) }, 'q = (atan2(y,x), length(p))', 'Unroll angles and radii into a texture plane. There is a branch seam at ±π; integer angular repetition can hide it.', (i, u) => `vec2(angleOf(${i.p})*${u.angleScale},length(${i.p})*${u.radiusScale})`),
    kaleidoscope: node('Angular mirror', 'Coordinates', 'coord', { p: 'coord' }, { sectors: num('Sectors', 6, 2, 24, 1), spin: num('Rotation speed', 0.1, -1, 1, 0.01) }, 'a = |mod(theta + π/n, 2π/n) − π/n|', 'Fold the angular coordinate into mirrored sectors. Reuse any source pattern to create symmetry.', (i, u) => `length(${i.p})*vec2(cos(abs(mod(angleOf(${i.p})+u_time*${u.spin}+PI/${u.sectors},TAU/${u.sectors})-PI/${u.sectors})),sin(abs(mod(angleOf(${i.p})+u_time*${u.spin}+PI/${u.sectors},TAU/${u.sectors})-PI/${u.sectors})))`),
    noise: node('Fractal value noise', 'Scalar fields', 'scalar', { p: 'coord' }, { frequency: num('Frequency', 3, 0.1, 30, 0.1), octaves: num('Octaves', 6, 1, 8, 1), speed: num('Flow speed', 0.1, -2, 2, 0.01), seed: num('Seed offset', 0, 0, 100, 1) }, 'f(p) = Σ 2⁻ᵏ noise(2ᵏ Rp + offset)', 'Smooth deterministic multiscale noise. Not part of the original nebula formulas; useful for new organic surfaces.', (i, u) => `fbm(${i.p}*${u.frequency}+vec2(${u.seed},u_time*${u.speed}),${u.octaves})`),
    waves: node('Nested cosine bands', 'Scalar fields', 'scalar', { p: 'coord' }, { frequency: num('Frequency', 9, 0.1, 80, 0.1), bend: num('Phase bending', 4, 0, 20, 0.1), speed: num('Phase speed', 0.5, -4, 4, 0.01) }, 'f = ½ + ½ cos(kx + b sin(ky − t))', 'A compact example of phase modulation: one wave bends another. It becomes marbling under a coordinate warp.', (i, u) => `(0.5+0.5*cos(${i.p}.x*${u.frequency}+${u.bend}*sin(${i.p}.y*${u.frequency}*0.65-u_time*${u.speed})))`),
    disc: node('Soft disc / sphere mask', 'Scalar fields', 'scalar', { p: 'coord' }, { radius: num('Radius', 1, 0.02, 3, 0.01), edge: num('Edge softness', 0.02, 0.001, 0.6, 0.001) }, 'mask = 1 − smoothstep(−edge, edge, |p| − radius)', 'Coverage mask. Connect to Mask layer, or use it to modulate another field.', (i, u) => `softInside(length(${i.p})-${u.radius},${u.edge})`),
    ring: node('Gaussian ring', 'Scalar fields', 'scalar', { p: 'coord' }, { radius: num('Radius', 1, 0, 3, 0.01), width: num('Width', 0.1, 0.005, 1, 0.005) }, 'f = exp(−((|p| − radius)/width)²)', 'A luminous rim with a hollow center. A Gaussian field, not a geometric mesh.', (i, u) => `gaussian(length(${i.p})-${u.radius},${u.width})`),
    threshold: node('Soft threshold', 'Scalar fields', 'scalar', { field: 'scalar' }, { level: num('Threshold', 0.5, -2, 2, 0.01), sharpness: num('Sharpness', 8, 0.1, 60, 0.1) }, 'f = exp(−exp(−sharpness · (field − level)))', 'The same nested-exponential gate used by the source equations. Turns smooth variation into wisps, islands or filaments.', (i, u) => `cutoff(-${u.sharpness}*(${i.field}-${u.level}))`),
    fieldmath: node('Combine scalar fields', 'Scalar fields', 'scalar', { a: 'scalar', b: 'scalar' }, { weightA: num('A weight', 1, -5, 5, 0.01), weightB: num('B weight', 1, -5, 5, 0.01), product: num('Product weight', 0, -5, 5, 0.01), bias: num('Bias', 0, -4, 4, 0.01) }, 'f = wa·a + wb·b + wp·a·b + bias', 'One small arithmetic node supports sums, differences, products and threshold offsets.', (i, u) => `(${u.weightA}*${i.a}+${u.weightB}*${i.b}+${u.product}*${i.a}*${i.b}+${u.bias})`),
    expression: node('Custom scalar equation', 'Authoring', 'scalar', { p: 'coord', a: 'scalar', b: 'scalar' }, { expression: expr('0.5 + 0.5*cos(8.0*r - 3.0*theta - t)') }, 'float f(p,a,b,t) = your expression', 'Compile an editable GLSL scalar expression. x,y,r,theta are derived from p. Additional scalar sockets a and b can carry any fields.', () => ''),
    vectorExpression: node('Custom coordinate equation', 'Authoring', 'coord', { p: 'coord', a: 'scalar', b: 'scalar' }, { expression: expr('rotate2(p, 0.5*sin(r*3.0-t))') }, 'vec2 q(p,a,b,t) = your expression', 'Author new coordinate maps without rewriting the renderer. Returns vec2; no JavaScript execution.', () => ''),
    colorExpression: node('Custom color equation', 'Authoring', 'layer', { p: 'coord', a: 'scalar', b: 'scalar' }, { expression: expr('spectrum(r - t*0.1, 0.0) * (0.5 + 0.5*cos(theta*6.0))') }, 'vec3 color(p,a,b,t) = your expression', 'Author RGB radiance. Returns vec3; alpha is set to one. Combine with a mask for transparency.', () => ''),
    palette: node('Two-color emission', 'Color & composition', 'layer', { field: 'scalar' }, { low: rgb('Low color', '#09212e'), high: rgb('High color', '#62edc3'), gain: num('Emission', 1, 0, 5, 0.01), power: num('Contrast power', 1, 0.1, 8, 0.05) }, 'RGB = gain · mix(low, high, clamp(field)^power)', 'Color a scalar field. This returns straight RGB with full coverage; add a mask when the layer should be transparent.', (i, u) => `vec4(mix(${u.low},${u.high},pow(clamp(${i.field},0.0,1.0),${u.power}))*${u.gain},1)`),
    solid: node('Solid color', 'Color & composition', 'layer', {}, { color: rgb('Color', '#030712'), gain: num('Gain', 1, 0, 4, 0.01) }, 'RGB = color × gain', 'A background or constant radiance layer.', (i, u) => `vec4(${u.color}*${u.gain},1)`),
    tint: node('Tint & gain', 'Color & composition', 'layer', { layer: 'layer' }, { color: rgb('RGB multiplier', '#ffffff'), gain: num('Gain', 1, 0, 5, 0.01) }, 'RGB = incoming RGB × tint × gain', 'Multiply floating-point radiance before output conversion. Does not discard highlight detail.', (i, u) => `vec4(${i.layer}.rgb*${u.color}*${u.gain},${i.layer}.a)`),
    mask: node('Mask layer', 'Color & composition', 'layer', { layer: 'layer', mask: 'scalar' }, { strength: num('Strength', 1, 0, 1, 0.01) }, 'alpha = alpha × mix(1, clamp(mask), strength)', 'Changes coverage, not straight RGB. Use Over to honor alpha; Add intentionally sums emitted RGB regardless of coverage.', (i, u) => `vec4(${i.layer}.rgb,${i.layer}.a*mix(1.0,clamp(${i.mask},0.0,1.0),${u.strength}))`),
    add: node('Add light', 'Color & composition', 'layer', { a: 'layer', b: 'layer' }, { gain: num('B gain', 1, 0, 5, 0.01) }, 'RGB = A.rgb + gain · B.rgb', 'Sum radiance before tone mapping. Alpha does not attenuate emission; use Over for opaque objects or alpha-masked layers.', (i, u) => `addLight(${i.a},${i.b},${u.gain})`),
    over: node('Front over back', 'Color & composition', 'layer', { front: 'layer', back: 'layer' }, {}, 'alpha = af + ab(1−af); RGB = (af Cf + (1−af)ab Cb)/alpha', 'Correct straight-alpha composition. Use it to hide background stars behind a planet, feathers, or a silhouette.', i => `overLayer(${i.front},${i.back})`),
    nebulaGeometry: node('Pinched shell family · S,A', 'Source nebula', 'geometry', { p: 'coord' }, { pinch: num('Neck pinch', 0.3, 0.05, 0.8, 0.005), shear: num('Shell shear', 0.15, -0.5, 0.6, 0.005), shells: num('Shell count', 27, 1, 27, 1) }, 'Lₛ = sqrt(Uₛ² + (2Rₛ^0.3 |Uₛ|^−0.3 Vₛ)²) − Rₛ', 'Exact structural port at defaults. Ordered soft first-hit selection produces S (texture coordinate), A (emission rim), and coverage. These are separate meanings.', (i, u) => `nebulaGeometry(${i.p},${u.pinch},${u.shear},${u.shells})`),
    ringGeometry: node('Replacement ring geometry', 'Source nebula', 'geometry', { p: 'coord' }, { radius: num('Radius', 1.1, 0.1, 2, 0.01), width: num('Rim width', 0.16, 0.01, 0.7, 0.01), flatten: num('Vertical compression', 1.5, 0.2, 3, 0.01) }, 'S=2d; A=0.22 exp(−(d/width)²); d=|scaled p|−radius', 'New geometry with the same interface as the pinched shell family. Reuse the entire original cloud machinery unchanged.', (i, u) => `ringGeometry(${i.p},${u.radius},${u.width},${u.flatten})`),
    geometryField: node('Inspect geometry channel', 'Source nebula', 'scalar', { geometry: 'geometry' }, { channel: num('0=warp · 1=rim · 2=coverage', 1, 0, 2, 1), gain: num('Display gain', 4, 0.1, 10, 0.1) }, 'f = geometry.warp / rim / coverage', 'Extract one named field for diagnosis, masks or further composition. The rim and coverage are deliberately not interchangeable.', (i, u) => `((${u.channel}<0.5)?${i.geometry}.warp:((${u.channel}<1.5)?${i.geometry}.rim:${i.geometry}.coverage))*${u.gain}`),
    nebulaTurbulence: node('Nested-cosine turbulence · E', 'Source nebula', 'scalar', { p: 'coord', geometry: 'geometry' }, { bands: num('Bands', 50, 1, 50, 1), speed: num('Phase speed', 0, -1, 1, 0.01) }, 'E = Σ (19/20)ˢ Dₛ(S,Qₛ)', 'Original 50-band signed modulation. It perturbs the filament threshold and central glow. Motion is an optional new phase shift, zero in source mode.', (i, u) => `nebulaTurbulence(${i.p},${i.geometry},${u.bands},u_time*${u.speed})`),
    nebulaCloud: node('Filaments & haze · K', 'Source nebula', 'layer', { p: 'coord', geometry: 'geometry', turbulence: 'scalar' }, { bands: num('Bands', 50, 1, 50, 1), detail: num('Sharp filament gain', 1, 0, 3, 0.01) }, 'Iₛ=45 C₁,ₛ+6 C₀,ₛ; Kᵥ=Σ Iₛ (19/20)ˢ κᵥ,ₛ', 'Original RGB field before the geometry rim and core cutout are applied. Preview looks over-bright because masking happens downstream.', (i, u) => `nebulaCloud(${i.p},${i.geometry},${i.turbulence},${u.bands},${u.detail})`),
    nebulaGas: node('Gas emission · Hgas', 'Source nebula', 'layer', { p: 'coord', geometry: 'geometry', turbulence: 'scalar', cloud: 'layer' }, { gain: num('Gas gain', 1, 0, 3, 0.01) }, 'Hgas = 1.1 (1−W) K A', 'Original gas contribution. A confines emission to shell rims; 1−W clears the central glow region.', (i, u) => `nebulaGas(${i.p},${i.geometry},${i.turbulence},${i.cloud},${u.gain})`),
    nebulaCore: node('Central glow · W', 'Source nebula', 'layer', { p: 'coord', turbulence: 'scalar' }, { gain: num('Core gain', 1, 0, 3, 0.01) }, 'W=exp(−exp(10|p|−1+E/4)); Hcore=W(2,2,3)', 'Original glow. The square root in the source contains x²+y² only, not −1 or E/4.', (i, u) => `nebulaCore(${i.p},${i.turbulence},${u.gain})`),
    nebulaStars: node('Folded star lattices · T', 'Source nebula', 'layer', { p: 'coord' }, { bands: num('Lattices', 30, 1, 30, 1), gain: num('Starlight', 1, 0, 3, 0.01) }, 'M,N=acos(cos(rotated coordinates)); T=Σ colored(center+halo)', 'Original deterministic stars with pointed centers. Folded-angle lattices, not random sprites or an astronomical catalog.', (i, u) => `nebulaStars(${i.p},${u.bands},${u.gain})`),
    scatterStars: node('Seeded star field', 'Astronomical studies', 'layer', { p: 'coord' }, { density: num('Density scale', 22, 3, 60, 1), gain: num('Starlight', 0.7, 0, 3, 0.01), seed: num('Seed', 17, 0, 100, 1), speed: num('Twinkle speed', 0.1, 0, 2, 0.01) }, 'star = Gaussian core + halo + cross rays', 'New deterministic jittered-cell stars. Three scales and warm/cool variation; distinct from the original folded lattice algorithm.', (i, u) => `scatterStars(${i.p},${u.density},${u.gain},${u.seed},u_time*${u.speed})`),
    planet: node('Cyclonic water planet', 'Astronomical studies', 'layer', { p: 'coord' }, { radius: num('Radius', 1.08, 0.1, 2, 0.01), cloud: num('Cloud cover', 0.65, 0, 2, 0.01), twist: num('Cyclone twist', 5, 0, 14, 0.1), light: num('Light angle', 2.25, 0, 6.28, 0.01), speed: num('Cloud drift', 0.5, -2, 2, 0.01) }, 'visible sphere → spherical coordinates → cyclone maps → clouds → lighting', 'Subject-inspired study, not the artist’s unretrieved formula. Rotated cloud coordinates, finite-octave noise, Lambert-like light, glint and rim scattering.', (i, u) => `waterPlanet(${i.p},${u.radius},${u.cloud},${u.twist},${u.light},u_time*${u.speed})`),
    atmosphere: node('Atmospheric rim', 'Astronomical studies', 'layer', { p: 'coord' }, { radius: num('Radius', 1.08, 0.1, 2, 0.01), gain: num('Glow', 0.7, 0, 3, 0.01) }, 'glow = Gaussian(|p|−radius)', 'An independent analytic limb glow; align its radius with the planet when composing them.', (i, u) => `atmosphere(${i.p},${u.radius},${u.gain})`),
    lens: node('Star-cluster lens map', 'Astronomical studies', 'coord', { p: 'coord' }, { strength: num('Deflection strength', 1, 0, 3, 0.01), count: num('Lenses', 7, 1, 12, 1), softening: num('Softening', 0.015, 0.001, 0.2, 0.001) }, 'β = θ − Σ mᵢ(θ−θᵢ)/(|θ−θᵢ|²+ε²)', 'Illustrative softened thin-lens backward mapping. Zero strength is the identity. Feed the result into a galaxy; draw foreground lens stars in the unwarped plane.', (i, u) => `clusterLens(${i.p},${u.strength},${u.count},${u.softening})`),
    clusterLights: node('Foreground cluster stars', 'Astronomical studies', 'layer', { p: 'coord' }, { gain: num('Brightness', 1, 0, 3, 0.01), count: num('Stars', 7, 1, 12, 1) }, 'centers share the lens map’s deterministic positions', 'Draw these AFTER lensing the background. Moving a background star image through this node would not model a foreground lens cluster.', (i, u) => `clusterLights(${i.p},${u.gain},${u.count})`),
    galaxy: node('Logarithmic spiral galaxy', 'Astronomical studies', 'layer', { p: 'coord' }, { arms: num('Spiral arms', 3, 1, 8, 1), pitch: num('Winding', 7, 0.5, 15, 0.1), radius: num('Scale', 0.75, 0.1, 2, 0.01), dust: num('Dust lanes', 0.6, 0, 1, 0.01), speed: num('Phase speed', 0.2, -2, 2, 0.01) }, 'phase = arms·theta − pitch·log(r+0.1)', 'New analytic spiral arms, Gaussian-like central bulge, radial fade, dusty modulation and emission knots. Its input coordinates can be gravitationally warped.', (i, u) => `spiralGalaxy(${i.p},${u.arms},${u.pitch},${u.radius},${u.dust},u_time*${u.speed})`),
    aurora: node('Spiral auroral curtain', 'Astronomical studies', 'layer', { p: 'coord' }, { turns: num('Winding', 4, 0.5, 12, 0.1), width: num('Ribbon width', 0.115, 0.01, 0.4, 0.005), curtain: num('Fine rays', 1, 0, 3, 0.01), speed: num('Flow speed', 0.5, -2, 2, 0.01) }, 'ribbon = exp(−[sin(theta + turns·log(r+0.12))/width]²)', 'New projected spiral ribbon with green/purple emission and angular striations. It illustrates appearance, not an auroral plasma simulation.', (i, u) => `auroraVortex(${i.p},${u.turns},${u.width},${u.curtain},u_time*${u.speed})`),
    disk: node('Accretion disk & shadow', 'Astronomical studies', 'layer', { p: 'coord' }, { radius: num('Shadow scale', 0.34, 0.06, 0.8, 0.005), inclination: num('Projection flattening', 3, 1, 7, 0.05), spin: num('Texture winding', 4, 0, 12, 0.1), speed: num('Flow speed', 0.5, -2, 2, 0.01) }, 'projected annulus + bent rear arc − central shadow', 'New stylized construction. The bright-side weighting and bent arc are artistic terms, not a relativistic transfer calculation.', (i, u) => `accretionDisk(${i.p},${u.radius},${u.inclination},${u.spin},u_time*${u.speed})`),
    tidal: node('Stretched star & tidal stream', 'Astronomical studies', 'layer', { p: 'coord' }, { stretch: num('Taper power', 2.5, 0.3, 6, 0.05), size: num('Star width', 0.13, 0.02, 0.4, 0.005), speed: num('Stream speed', 0.5, -2, 2, 0.01) }, 'emission = Gaussian(distance to tapered centerline) + star core', 'New narrow curved stream broadening toward a luminous star. Independent from the disk so it can be translated, masked or reused as a comet.', (i, u) => `tidalStream(${i.p},${u.stretch},${u.size},u_time*${u.speed})`),
    feather: node('Single eyespot feather', 'Natural studies', 'layer', { p: 'coord' }, { width: num('Width', 0.095, 0.02, 0.3, 0.005), eye: num('Eyespot scale', 1, 0.3, 2, 0.01), speed: num('Barb motion', 0.2, 0, 2, 0.01) }, 'tapered local silhouette + oblique cosine barbs + nested eyespot rings', 'Reusable analytic stamp. Base at (0,0), tip at (0,1). No texture. The fan node instances this exact kernel many times.', (i, u) => `feather(${i.p},${u.width},${u.eye},u_time*${u.speed})`),
    fan: node('Peacock feather fan', 'Natural studies', 'layer', { p: 'coord' }, { spread: num('Fan spread', 2.9, 0.4, 3.5, 0.01), rows: num('Feather rows', 4, 1, 4, 1), width: num('Feather width', 0.095, 0.03, 0.2, 0.005), speed: num('Breeze speed', 0.3, 0, 2, 0.01) }, 'fan = Overᵢ feather(Rᵢ(p−base)/lengthᵢ)', 'New full-display construction, not a recovered 2026 formula. Outer-to-inner rows, shared feather kernels and staggered phase give repeated yet varied detail.', (i, u) => `peacockFan(${i.p},${u.spread},${u.rows},${u.width},u_time*${u.speed})`),
    peacockBody: node('Peacock body & crest', 'Natural studies', 'layer', { p: 'coord' }, { size: num('Size', 1, 0.3, 2, 0.01) }, 'body ellipses + curved neck + head + crest segments', 'A separate opaque silhouette over the feather fan, so changing the fan does not distort the bird.', (i, u) => `peacockBody(${i.p},${u.size})`),
    fire: node('Tapered flame field', 'Natural studies', 'layer', { p: 'coord' }, { height: num('Height', 2, 0.2, 3, 0.01), width: num('Base width', 0.8, 0.1, 2, 0.01), turbulence: num('Turbulence', 1, 0, 2, 0.01), speed: num('Rise speed', 1, 0, 3, 0.01) }, 'tapered silhouette + advected noise + heat palette', 'New explanatory fire study. Moving the sampling coordinates creates upward flow without storing a simulation state. Not a reconstruction of the linked video.', (i, u) => `firePlume(${i.p},${u.height},${u.width},${u.turbulence},u_time*${u.speed})`),
    hedgehog: node('Hedgehog & quill field', 'Natural studies', 'layer', { p: 'coord' }, { quills: num('Quill length', 0.28, 0.02, 0.7, 0.01), density: num('Quill count', 160, 10, 160, 1), speed: num('Breathing speed', 0.5, 0, 2, 0.01) }, 'elliptical body + repeated tapered segment quills + facial masks', 'New constructive hedgehog example. Separate local stamps supply a readable silhouette and repeated surface detail; no claim about the inaccessible video steps.', (i, u) => `hedgehog(${i.p},${u.quills},${u.density},u_time*${u.speed})`)
};
export const typeNames = { coord: 'Coordinates · vec2', scalar: 'Scalar field · float', geometry: 'Geometry · S/A/coverage', layer: 'Radiance + alpha · vec4' };
export const zeroByType = { coord: 'vec2(0)', scalar: '0.0', geometry: 'Geometry(0.0,0.0,0.0)', layer: 'vec4(0)' };
export function parameterDefaults(type) {
    if (!Object.hasOwn(catalog, type)) {
        throw new Error(`Unknown component: ${type}`);
    }
    return Object.fromEntries(Object.entries(catalog[type].params).map(([key, spec]) => [key, spec.value]));
}
