/** Evidence ledger. Search-index captions are not the original formula sheets.
 * These distinctions also appear inside the app, not only in the README.
 */
export const sources = [
    { title: 'Stormy water planet', url: 'https://x.com/naderi_yeganeh/status/2099486463528153310', status: 'Caption indexed · formulas unavailable', note: 'The exact post’s subject was located in search. Direct X retrieval was blocked; its full-resolution image/equations were not recovered. Our planet is a new subject-based construction.', scene: 'water' },
    { title: 'Galaxy lensed by a star cluster', url: 'https://x.com/naderi_yeganeh/status/2098386890013479111', status: 'Caption indexed · formulas unavailable', note: 'Subject confirmed by the indexed primary caption. The original formula sheet was not retrieved. Our softened lens map is an explicit illustrative model, not a transcription.', scene: 'lensing' },
    { title: 'Spiral aurora / auroral vortex', url: 'https://x.com/naderi_yeganeh/status/2094384568648261800', status: 'Caption indexed · formulas unavailable', note: 'Subject confirmed by the indexed primary caption. The logarithmic spiral and fine curtain in this app are our own recipe.', scene: 'aurora' },
    { title: 'Black hole stretching a star', url: 'https://x.com/naderi_yeganeh/status/2089682273930998050', status: 'Caption indexed · formulas unavailable', note: 'Subject confirmed by the indexed primary caption. A related artist LinkedIn caption was also retrievable, but not the complete equations. Our disk/stream are stylized, not ray-traced relativity.', scene: 'tidal' },
    { title: 'Peacock in full display', url: 'https://x.com/naderi_yeganeh/status/2083165498674426049', status: 'Caption indexed · formulas unavailable', note: 'The requested post’s caption was indexed. An older 2024 artist-posted peacock thumbnail was visible; it is not the requested 2026 formula sheet and was not substituted for it.', scene: 'peacock' },
    { title: 'Hedgehog method video announcement', url: 'https://x.com/naderi_yeganeh/status/1881707698640551955', status: 'Announcement confirmed · video not inspected', note: 'The indexed post and artist’s YouTube channel identify a short animation about the construction scenario. The video frames/transcript were not retrieved. Our hedgehog is an original teaching example.', scene: 'hedgehog' },
    { title: 'Fire method video announcement', url: 'https://x.com/naderi_yeganeh/status/1884272742159057270', status: 'Announcement confirmed · video not inspected', note: 'The indexed post and artist’s channel confirm the Fire scenario video. We did not recover its content and do not attribute our fire algorithm to that video.', scene: 'fire' },
    { title: '2023 explanation thread', url: 'https://x.com/naderi_yeganeh/status/1610740065763745792', status: 'User-described · content not retrieved', note: 'Direct retrieval and exact-ID searches did not recover the text. No quote, claim about its contents, or reconstructed thread is presented.' },
    { title: 'Deedy’s Rust debugging post', url: 'https://x.com/deedydas/status/1863051658022023477', status: 'User-described · content not retrieved', note: 'The Rust experiment is described in the request; its source code and debugging exchange were not recovered. The port uses our own CPU/GPU tests, not a claimed diagnosis of that implementation.' },
    { title: 'Forward vs. inverse-design reply', url: 'https://x.com/aussetg/status/2102138297623433273', status: 'User-described · content not retrieved', note: 'The reply text was not recovered. The forward-rendering / inverse-design distinction below is our analysis, not an attributed quotation.' },
    { title: 'How to Draw with Math · artist-authored essay', url: 'https://www.scientificamerican.com/blog/guest-blog/how-to-draw-with-math/', status: 'Primary text read · 9 January 2017', note: 'The artist describes incrementally adding mathematical expressions to make a drawing resemble a chosen object. Periodicity, boundedness and smoothness make sine/cosine useful. This is evidence for deliberate, iterative design.' },
    { title: 'Pictures from Networks of Mathematical Functions', url: 'https://doi.org/10.1080/10724117.2024.2368373', status: 'Primary text retrieved · Math Horizons, 2024', note: 'The author describes designing a multi-step scenario, repeatedly running candidate functions, and using a network of auxiliaries to keep the final definition compact. Full short text retrieved through Exa; DOI metadata also indexed.' },
    { title: 'Artist’s YouTube channel', url: 'https://www.youtube.com/@naderiyeganeh', status: 'Video titles indexed · playback unavailable', note: 'The channel’s indexed listing corroborates the Hedgehog and Fire video titles. Channel shell retrieval supplied no video transcript.' }
];
export const methodNotes = [
    ['The final renderer runs forward', 'A compact program maps coordinates and time to RGB: image = R(equations, parameters, x, y, t). This app executes that program directly, with no photographic texture, neural network, or external asset in the artwork renderer.'],
    ['Design can work toward a target', 'Choosing the subject first, then inventing and refining functions, is an inverse design problem in the broad sense. It is compatible with the finished image being generated entirely by equations.'],
    ['Automatic fitting is a separate claim', 'The recovered primary accounts establish iterative equation design, not a pixel-loss optimizer, image tracing system, or generative model. A finished formula cannot uniquely disclose how it was found.'],
    ['Reproducibility is not authorship history', 'A program that reproduces pixels validates a construction, not the route the artist took to discover it. The supplied nebula has a numerical reference; the five new subject studies do not have recovered source formulas.'],
    ['Reusable function networks', 'Coordinate maps → shapes and fields → detail → radiance/coverage → composition → display. A directed graph makes this network explicit and lets one shared subexpression feed several downstream components.']
];
